"""Initial migrate

Revision ID: 2991c741b47e
Revises: 
Create Date: 2022-09-05 17:07:51.884098

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2991c741b47e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=20), nullable=True),
        sa.Column('faltas', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materia',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=True),
        sa.Column('docente', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materia')
    op.drop_table('aluno')
    # ### end Alembic commands ###
